# Generated by Django 2.2.4 on 2019-12-25 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191226_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desctiption',
            new_name='description',
        ),
    ]
