# Generated by Django 2.2.4 on 2019-12-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191226_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='desctiption',
        ),
    ]
