# Generated by Django 2.2.4 on 2019-12-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_betalike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betalike',
            name='bl',
            field=models.IntegerField(default=0),
        ),
    ]
