# Generated by Django 2.2.4 on 2019-12-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191226_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BetaLike',
        ),
    ]
