# Generated by Django 2.2.4 on 2019-12-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
