# Generated by Django 2.2.4 on 2019-12-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191227_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAPI',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
    ]
