# Generated by Django 2.2.4 on 2019-12-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_postapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAPI',
        ),
    ]
