# Generated by Django 2.2.4 on 2020-01-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
